### ISSUE TITLE
Is this the right way to get current stocks?

### ISSUE THREAD

**Issue by carsonpo** [robinhood-unofficial/Robinhood#102]
Will this code below give me a list of string ticker names for the current securities owned (portfolio), and will my next if statement do something if a ticker that I pass is not in the portfolio list?

Basically I'm asking if my code will function how I'm thinking.

```
curpos = hood.securities_owned()
    
    for position in curpos['results']:
        portfolio.append(json.dumps(position,indent=3))
    
    if ticker not in portfolio:
        # do something
```

Thanks

**Comment by jsmwoolf** [comment]
Hi @carsonpo,

I'm afraid that code will not do what you're looking for.  You are on the right track, however.

If you're wanting to store only the tickers, you'll need to first retrieve the instrument ID and then make a call to retrieve the stock information.

Here is the code that'll do what you want.
```python
curpos = hood.securities_owned()
portfolio = []

for position in curpos['results']:
    curinst = position['instrument'].split('/')[-2]
    portfolio.append(hood.instrument(curinst)['symbol'])

if ticker not in portfolio:
    # do something
```

Hope that helps.

**Comment by jasonleehodges** [comment]
@carsonpo Did this help you find a resolution to your problem?

**Comment by gkyriakou** [comment]
Hey all,

Ended up here because of a `Robinhood.exceptions.InvalidInstrumentId`.
The logic of @jsmwoolf is sound, however, it returns the same `Robinhood.exceptions.InvalidInstrumentId` for me.

For reference, the id that I am using (and the result of `print curinst` before calling `hood.instrument(curinst)`) is: 54db869e-f7d5-45fb-88f1-8d7072d4c8b2

I tried with multiple ids with the same results. Any ideas?
