### ISSUE TITLE
Helper for company metadata

### ISSUE THREAD

**Issue by lockefox** [robinhood-unofficial/Robinhood#41]
I've been wanting a `get_info()` function that operates more like [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#yahoo-finance-quotes).  It's kinda the defacto quick resource for finance for python.

Unfortunately, it requires 3 pulls from Robinhood to mimic the [1 pull from Yahoo](http://wern-ancheta.com/blog/2015/04/05/getting-started-with-the-yahoo-finance-api/)

* `/quote`: for prices
* `/fundamentals`: for company info
* `/instruments`: for company name and market info

**Comment by Jamonek** [comment]
I have started on a similar function now.

**Comment by bdowling** [comment]
Should we possibly start a Robinhood.utils library for these 'helper' functions?  I thought about the same when adding the cancel_orders_all, etc..  It's not exactly a core function.

**Comment by lockefox** [comment]
@bdowling I would not be against reorganizing tools to split "data" and "functional" utilities.

I'd probably push to have a Robinhood parent class with auth that children can inherit.  I've been digging into the structure of `pandas_datareader` which might have some architecture notes: https://github.com/pydata/pandas-datareader

**Comment by Jamonek** [comment]
Yes, we should.

**Comment by ciresnave** [comment]
@bdowling @lockefox @Jamonek I, too, was thinking there was need to split core API functionality from the helper functions that make it usable.  You three appear to be the core developers pushing this forward before I got here so...has anyone started work on splitting this?  Also, what is the general plan for this library moving forward?  Do we even have a plan yet or are each of us just winging it and adding features as we need them and fixing problems as they're found?  More specific to THIS issue, should we be looking at adding calls to other APIs that would be useful to people using this library?  For instance, Yahoo Finance and Google Finance both still have some calls that work and could be used to pull data that could be used in programs that then use Robinhood to place actual orders.  Of course, those calls should NOT be part of the Robinhood library or the Robinhood.utils library. Maybe a higher level library called something like Stocks (and maybe Stocks.utils) should be built?  If we do go that route does that change how we build the Robinhood library from this point forward?  

Obviously there are a lot of ideas and possibly different paths forward.  If any of you are willing to discuss the future of this library I would like to be part of that discussion...maybe with Jamonek heading it since this is his baby originally?

**Comment by ciresnave** [comment]
This seemed like a bad place for me to have started a discussion about the future of this library so I started a wiki page.  It's not set in stone but should give us a place to organize ideas.

**Comment by jasonleehodges** [comment]
> I'd probably push to have a Robinhood parent class with auth that children can inherit. 

I think this definitely needs to happen. Way too much scrolling going on when adding functionality to this library given that all the methods belong to one main class.

**Comment by Jamonek** [comment]
The wiki will be helpful as we begin to split up the library. I’d like to communicate via Slack or some other form of communication to coordinate with others as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasonleehodges** [comment]
I agree - a Slack channel would be awesome. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lockefox** [comment]
[Gitter](https://gitter.im/) is a much easier to manage public-portal for dev chat.

**Comment by lockefox** [comment]
Also started work on a [REST-aware crawler RH library](https://github.com/lockefox/pyRobinhood) but got hung up on the testing concerns vs credentials.  Would very much like to push for a magic-method crawler design to simplify the upkeep over time

**Comment by jasonleehodges** [comment]
> Also started work on a REST-aware crawler RH library but got hung up on the testing concerns vs credentials. Would very much like to push for a magic-method crawler design to simplify the upkeep over time

This seems like a really cool design approach. However, this would only work for those endpoints that are returned by a basic get request to api.robinhood.com right? How would this handle some of the more hidden endpoints, like the new tagging endpoints that are being used on Robinhood Web or the options endpoints that I've been able to sniff out from the native app?

**Comment by Jamonek** [comment]
The Gitter has been created.

**Comment by lockefox** [comment]
@jasonleehodges yes... this was started before they started rolling out private endpoints for options/crypto. 

My roadblocks have been:

* Getting samples for beta routes
* Validating auth endpoints in CI
* Starting somewhere other than root
* (advanced) pandas-datareader style ability for better `requests` plugins

I don't think this is the be-all for the customer-facing API, but would go a very long way to adding robustness to the top-level calls like `get_quotes()` or `place_order()`
