### ISSUE TITLE
Standard Authentication "store"

### ISSUE THREAD

**Issue by bdowling** [robinhood-unofficial/Robinhood#43]
What are the thoughts on having a standard credential store method for this library?  In scope?  Out?

For example I tried this with the keyring module:

```
import keyring
import os
keyring.set_keyring( keyring.backends.kwallet.DBusKeyring() )
username = os.getenv('RHUSER',os.getenv('USER'))
password = keyring.get_password('rhAPI', username)

rh = Robinhood();
rh.login(username=username, password=password)
```
https://pypi.python.org/pypi/keyring

Of course not everyone is going to match their local and online usernames as I was, but we could also have a dotFile somewhere with that for example.  keyring could also fallback to using a flatfile, but I like to encourage using an encrypted stores.

**Comment by Jamonek** [comment]
In scope! Lets discuss more then implement.

**Comment by TomFaulkner** [comment]
I'm late to teh game here, but why save username and password when the token is available? I did a pull request to @bdowling on his most recent branch to add token getter/setter properties. It seems the token doesn't change, which makes sense, so it would probably be better to work from the token rather than the credentials.

**Comment by jasonleehodges** [comment]
Has anyone thought more on this? Perhaps set the token as an environment variable `os.environ['rh_token']` and check if it exists within the environment. If it does not exist prompt for login and then store the token in the environment.
