### ISSUE TITLE
Proposal: Convert all monetary and fractional values to Decimal

### ISSUE THREAD

**Issue by bdowling** [robinhood-unofficial/Robinhood#58]
I'd like to suggest that this library do Decimal conversion internally for any results returned that are monetary or other fractional values.

In my own use I ran into the floating point accuracy issues, and have done this conversion client-side, but it would be cleaner in the library.

**Comment by bdowling** [comment]
Just, fwiw, I did this on https://github.com/bdowling/Robinhood/tree/fix_place_order_and_waymore_module_rename and so far so good, no issues.  Need to develop some better tests though.

I had encountered float comparison issues in the past, not being able to do trailing stop losses for example because comparing quote prices with floats is not precise enough.

**Comment by lockefox** [comment]
Converting numbers for people without strictly described behavior is risky.  It is possible to use py's [Decimal](https://docs.python.org/3/library/decimal.html) library, but we would have to be explicit about that behavior.

I think "less is more" in this case.  The core value of this library is "accessing the API".  And we should prob let users do the conversion for themselves rather than run the risk of being inaccurate.
