### ISSUE TITLE
Separate functionality

### ISSUE THREAD

**Issue by Jamonek** [robinhood-unofficial/Robinhood#85]
I’m thinking about splitting up the framework into a format such as main class / helper classes. How does everyone feel about this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciresnave** [comment]
I agree completely. The actual API should be separated from code designed to make it more user friendly.

**Comment by jasonleehodges** [comment]
Yes - I agree with this and would love to help out. The main class should be a parent with only the functionality that needs to be shared across all the children classes (like authentication). Also - it would be nice for the authentication to follow a decorator pattern so that certain methods in the children can be decorated with @auth-required to prompt them to login if they are using a method and have not yet logged in. 

I also found some new endpoints for options that require a Bearer/oauth authentication so there is a helper endpoint for that which would be nice to add in order to convert standard tokens to oath tokens.

Another cool thing to add if there is going to be a refactor is type hinting, that way all the types don't have to be described in the method descriptions but in the function parameters themselves. Might also look into the enforce module to enforce the types for stricter code with more predictable outcomes.

**Comment by ciresnave** [comment]
I like Jason's suggestion of using a decorator to automatically trigger a log in and/or OAuth token conversion before any method that requires authentication. We would need to make the log in functionality pluggable in some way because what works for a command line app will not work for a GUI app or a web app or...etc. Still... it's a great idea.

**Comment by jasonleehodges** [comment]
> We would need to make the log in functionality pluggable in some way because what works for a command line app will not work for a GUI app or a web app

I see this working the same as Django or Flask frameworks handling API/Route endpoints with a login decorator. Any page in a web app or GUI that requires authentication would use the decorator to determine whether or not they are logged in - if true the decorator will return a token that can be used for the existing request, if false the developer will handle the exception by either prompting them with the login_prompt() method (for command line apps) or redirecting to a login page (for web or GUI apps).
